test sql publish

diff --git a/.github/workflows/dotnetcore.yml b/.github/workflows/dotnetcore.yml
--- a/.github/workflows/dotnetcore.yml
+++ b/.github/workflows/dotnetcore.yml
@@ -54,8 +54,43 @@ jobs:
   #         name: CodeQuality
   #         path: CodeQuality
   
-  unit_test_db_mssql:
+  test:
     runs-on: ubuntu-latest
+    # Service containers to run with `runner-job`
+    # services:
+    #   # Label used to access the service container
+    #   redis:
+    #     # Docker Hub image
+    #     image: mcr.microsoft.com/mssql/server:2019-latest
+    #     #
+    #     ports:
+    #       # Opens tcp port 6379 on the host and service container
+    #       - 1433:1433
+    #     env:
+    #       GIT_SUBMODULE_STRATEGY: recursive
+    #       ACCEPT_EULA: Y
+    #       SA_PASSWORD: yourStrong(!)Password
+    steps:
+    - uses: actions/checkout@v1
+    - name: Setup .NET Core
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 3.1.401
+    - name: build dacpac
+        run: |
+          cd src/SQLCover/DatabaseProject.Build
+          dotnet restore
+          dotnet build --configuration Release
+      # cd $GITHUB_WORKSPACE
+    # Upload dacpac
+    - name: upload
+      uses: actions/upload-artifact@v1
+      with:
+        name: dacpac-package
+        path: ./src/SQLCover/DatabaseProject.Build/bin/Release/netstandard2.0/
+  deploy-sqlpackage:
+    runs-on: ubuntu-latest
+    needs: test
     # Service containers to run with `runner-job`
     services:
       # Label used to access the service container
@@ -71,15 +106,70 @@ jobs:
           ACCEPT_EULA: Y
           SA_PASSWORD: yourStrong(!)Password
     steps:
+    # Download artifacts
+    - name: download-artifact
+      uses: actions/download-artifact@v1
+      with:
+        name: dacpac-package
+        path: ~/dacpac-package
+    # Download sqlpackage
+    - name: download sqlpackage
+      run: >
+        curl -L https://go.microsoft.com/fwlink/?linkid=2113331 --output sqlpackage.zip &&
+        unzip sqlpackage.zip -d ~/sqlpackage &&
+        chmod a+x ~/sqlpackage/sqlpackage
+    # Run sqlpackage
+    - name: sqlpackage publish
+      run: >
+        ~/sqlpackage/sqlpackage
+        /Action:Publish
+        /SourceFile:~/dacpac-package/DatabaseProject.Build.dacpac
+        /Properties:IncludeCompositeObjects=True
+        /TargetServerName:localhost
+        /TargetUser:sa
+        /TargetPassword:yourStrong(!)Password
+        /TargetDatabaseName:DatabaseProject
+
+    # Dump logs of the container if something failed
+    - name: Dump docker logs on failure
+      if: failure()
+      uses: jwalton/gh-docker-logs@v1
+
+  # Attempt to deploy a project to a SQL Server instance running in a container using dotnet publish
+  deploy-publish:
+    runs-on: ubuntu-18.04
+    needs: test
+    services:
+      sqlserver:
+        image: mcr.microsoft.com/mssql/server:2019-latest
+        env:
+          ACCEPT_EULA: Y
+          SA_PASSWORD: JdMsKZPBBA8kVFXVrj8d
+        ports:
+          - 1433:1433
+        options: >-
+          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'JdMsKZPBBA8kVFXVrj8d' -Q 'SELECT 1' || exit 1"
+          --health-interval 10s
+          --health-timeout 3s
+          --health-retries 10
+          --health-start-period 10s
+    # Fetch sources
+    steps:
     - uses: actions/checkout@v1
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 3.1.401
-    - name: build dacpac
-        run: |
-          cd src/SQLCover/DatabaseProject.Build
-          dotnet build
+    # Publish the project
+    - name: publish project
+      run: dotnet publish ./test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj /p:TargetUser=sa /p:TargetPassword=JdMsKZPBBA8kVFXVrj8d /bl /p:DependencyVersion="1.*-*" /warnaserror:SQL71502
+
+    # Dump logs of the container if something failed
+    - name: Dump docker logs on failure
+      if: failure()
+      uses: jwalton/gh-docker-logs@v1
+
+
     # - name: enabledb
     #   run: cp ./src/SQLCover/Data/appSettings.bitbucket.mssql.json ./src/SQLCover/Data/AppSettings.json
     # - name: install nbgv
